spring:
  datasource:
    url: jdbc:mysql://localhost:3306/platform
    username: root
    password: Sako1998
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: "thisIsASecretKeyThatIsLongEnoughToBeUsedWithHS512Algorithm1234567890"
logging:
  file:
    name: log.txt
  level:
    root: INFO
    SellingExchangePlatform: INFO
